version: '3'

services:
  client:
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    user: "${UID}:${GID}"
    environment:
      - VITE_API_URL=http://localhost:8000
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

  server:
    build: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - DATABASE_NAME=xenotrade
      - DEBUG=1
      - PYTHONDONTWRITEBYTECODE=1
    depends_on:
      - mongodb
    user: "${UID}:${GID}"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    command: mongod --quiet --logpath /dev/null

volumes:
  mongodb_data:
